spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    enabled: true
    drop-first: false
#    change-log: classpath:db.changelog/changelog.yaml
    default-schema: public
#  liquibase:
#    change-log: classpath:../db/changelog/changelog.xml

